## Importing Libraries

In [19]:
import numpy as np
import scipy
from scipy import stats

__Example 4.4.1__ (Applying concept of hypergeometric distribution) Let us consider the probability of
getting x spades in a hand of bridge. In the framework above, A denotes a spade and A¯ denotes any card
other than a spade. Hence N = 52, N1 = 13, N2 = N − N1 = 39. If X denotes the number of spades
in a hand of n = 13 cards, X has the sample space max[0, 13 − (52 − 13)] ≤ x ≤ min[13, 13], that is,
0 ≤ x ≤ 13, and X has probability function given by:

\begin{equation}
h(x) =  \frac{{13 \choose x}{39 \choose 13-x}}{52 \choose 13}
\end{equation}

In [20]:
# initializing a distribution
# parameters: M, n, N
# M: size of the population (which is 52 in our example)
# n: number of successes in population (which is 13 in our example since there are 13 spades)
# N: sample size (which is 13 in our example since we are considering for a hand of 13 cards)

rv = stats.hypergeom(52, 13, 13)
x = np.arange(0, 13 + 1)  # we want to find out probabilities of getting 0 -> 13 spades in our hand
pmf_spades = rv.pmf(x)  # creating a probability mass function for our X's 

print(pmf_spades)
print()  # just adding space between outputs 
print(pmf_spades[6 + 1])  # probability of getting 6 spades (+1 because indexing starts at 0)

[1.27909480e-02 8.00618599e-02 2.05873354e-01 2.86329607e-01
 2.38608006e-01 1.24691926e-01 4.15639753e-02 8.81660082e-03
 1.16690305e-03 9.26113531e-05 4.11606014e-06 9.10185289e-08
 7.98408148e-10 1.57476952e-12]

0.008816600816408794


__Example 4.6.1__ (Gambling and probabilities) Two dice are thrown 100 times and the number of nines is recorded. It is apparent that we are examining each roll of the two dice for the events nine or non-nine. The probability of obtaining a nine by throwing two dice is 4/36 = 1/9, that is, p = 1/9. Find the probability that x number of nines occur, where x = 0, 1, 2, ..., 6

In [21]:
# Binomial Distribution
# parameters: k, n, p
# k: number of successes 
# n: size of sample
# p: probability of success 

pmf_dices = stats.binom.pmf(np.arange(0, 6 + 1), 100, 0.111)  # probability mass function of getting 0 -> 6 9's when rolling 2 dice 100 times
pmf_dices

array([7.76561932e-06, 9.69610511e-05, 5.99271648e-04, 2.44427334e-03,
       7.40086924e-03, 1.77421063e-02, 3.50750865e-02])

__Example 4.8.3__ A manufacturing company of car parts found that one of its machines randomly produces
some defective parts. Further the company determined that X, the number of defective parts it produces
in each shift, is distributed by the Poisson distribution with mean λ = 3. Find using Python the probability
that it will produce x number of defective parts in the next two shifts, where x = 0, 1, 2, ..., 10

In [22]:
# Poisson Distribution
# parameters: k, mu
# k: number of "successes" or in our example, number of defective parts in the next two shifts 
# mu: or lambda, or mean, which is 3 in our example

pmf_defects = stats.poisson.pmf(np.arange(0, 10 + 1), 3)  # probability mass function of finding 0 -> 10 number of defective parts
pmf_defects

array([0.04978707, 0.14936121, 0.22404181, 0.22404181, 0.16803136,
       0.10081881, 0.05040941, 0.02160403, 0.00810151, 0.0027005 ,
       0.00081015])

__Example 4.9.1__ (Negative binomial probabilities) Two dice are thrown and the sum of the dots obtained
on the uppermost faces are recorded. What is the probability that a 7 occurs for the third time on the
x th throw where (x ≥ 3)?

In [23]:
# Negative Binomial Distribution
# parameters: k, n, p
# k: number of 'failures', which is 3 or more in our example 
# n: number of 'successes', which is 3 in our example
# p: probability of success in a single trial, which is 0.1667 in our example

pmf_ndices = stats.nbinom.pmf(np.arange(3, 16 + 1), 3, 0.1667)  # pmf that 7 occurring for the 3rd time on the xth throw, where 3<=x<=16
pmf_ndices

array([0.0268047 , 0.03350453, 0.03908706, 0.04342833, 0.04652849,
       0.04846524, 0.04936077, 0.0493588 , 0.04860899, 0.04725685,
       0.04543746, 0.04327204, 0.04086641, 0.03831072])